sonar.projectKey=Elenadelatorre_tfm-devsecops-supplychain
sonar.organization=elenadelatorre

# Rutas a analizar
sonar.sources=app/src
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/node_modules/**,**/test/**